package com.hive

val SENTENCES = arrayOf(
    "Gary didn't understand why Doug went upstairs to get one dollar bills when he invited him to go cow tipping.",
    "Fluffy pink unicorns are a popular status symbol among macho men.",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "He hated that he loved what she hated about hate.",
    "It's never comforting to know that your fate depends on something as unpredictable as the popping of corn.",
    "I became paranoid that the school of jellyfish was spying on me.",
    "It was always dangerous to drive with him since he insisted the safety cones were a slalom course.",
    "She had convinced her kids that any mushroom found on the ground would kill them if they touched it.",
    "If you like tuna and tomato sauce, try combining the two, it’s really not as bad as it sounds.",
    "Most shark attacks occur about 10 feet from the beach since that's where the people are.",
    "I always dreamed about being stranded on a desert island until it actually happened.",
    "Pink horses galloped across the sea.",
    "It took him a month to finish the meal.",
    "His ultimate dream fantasy consisted of being content and sleeping eight hours in a row.",
    "Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.",
    "The urgent care center was flooded with patients after the news of a new deadly virus was made public.",
    "The thunderous roar of the jet overhead confirmed her worst fears.",
    "I ate a sock because people on the Internet told me to.",
    "It was at that moment that he learned there are certain parts of the body that you should never Nair.",
    "I met an interesting turtle while the song on the radio blasted away.",
    "The lake is a long way from here.",
    "The green tea and avocado smoothie turned out exactly as would be expected.",
    "The river stole the gods.",
    "The Guinea fowl flies through the air with all the grace of a turtle.",
    "She tilted her head back and let whip cream stream into her mouth while taking a bath.",
    "We have a lot of rain in June.",
    "I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.",
    "If you don't like toenails, you probably shouldn't look at your feet.",
    "The Great Dane looked more like a horse than a dog.",
    "He ran out of money, so he had to stop playing poker.",
    "The skeleton had skeletons of his own in the closet.",
    "This made him feel like an old-style rootbeer float smells.",
    "Whenever he saw a red flag warning at the beach he grabbed his surfboard.",
    "There's a growing trend among teenagers of using frisbees as go-cart wheels.",
    "The three-year-old girl ran down the beach as the kite flew behind her.",
    "I covered my friend in baby oil.",
    "He played the game as if his life depended on it and the truth was that it did.",
    "I may struggle with geography, but I'm sure I'm somewhere around here.",
    "They finished building the road they knew no one would ever use.",
    "Patricia loves the sound of nails strongly pressed against the chalkboard.",
    "Best friends are like old tomatoes and shoelaces.",
    "Shakespeare was a famous 17th-century diesel mechanic.",
    "The murder hornet was disappointed by the preconceived ideas people had of him.",
    "Blue sounded too cold at the time and yet it seemed to work for gin.",
    "He kept telling himself that one day it would all somehow make sense.",
    "Jeanne wished she has chosen the red button.",
    "You'll see the rainbow bridge after it rains cats and dogs.",
    "To the surprise of everyone, the Rapture happened yesterday but it didn't quite go as expected.",
    "The overpass went under the highway and into a secret world.",
    "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
)

val NAMES = listOf(
    "Zahir Ahmose",
    "Damião Irma",
    "Hjördís Vittoria",
    "Mykhaylo Ganesh",
    "Jayanta Max",
    "Tamela Renato",
    "Eochaidh Dimos",
    "Philomel Varlaam",
    "Wafiya Siw",
    "Matilda Mandla",
    "Silverio Manoj",
    "Aeson Kincső",
    "Kshitij Evgeni",
    "Antigonos Guðríðr",
    "Gunter Drahoslav",
    "Adrijan Valentim",
    "Pratibha Marcellus",
    "Dobrilo Jožefa",
    "Prasad Kerttu",
    "Esther Om",
    "Venuše Gwladus",
    "Allison Romualdo",
    "Sigmundr Félicien",
    "Thekla Emilie",
    "Griogair Emer",
    "Charlemagne Giana",
    "Gemma Amalaric",
    "Raghnall Golnaz",
    "Leopold Souad",
    "Elouise Milorad"
)

val HUMAN_IMAGES = listOf(
    "https://images.gr-assets.com/authors/1611692824p5/19734894.jpg",
    "https://images.gr-assets.com/authors/1530190722p5/15284720.jpg"
)

val STATES = listOf(
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
)

val CITEIS = listOf(
    "Abidjan",
    "Addis Ababa",
    "Ahmedabad",
    "Aizawl",
    "Amaravati",
    "Ankara",
    "Baghdad",
    "Bangalore",
    "Bangkok",
    "Beijing",
    "Belo Horizonte",
    "Bengaluru",
    "Berlin",
    "Bhopal",
    "Bhubaneswar",
    "Buenos Aires",
    "Busan",
    "Cairo",
    "Caracas",
    "Casablanca",
    "Chandigarh",
    "Chengdu",
    "Chennai",
    "Chicago",
    "Chongqing",
    "Delhi",
    "Dhaka",
    "Dispur",
    "Dongguan",
    "Faisalabad",
    "Fortaleza",
    "Gairsain",
    "Gandhinagar",
    "Gangtok",
    "Guadalajara",
    "Guangzhou",
    "Hangzhou",
    "Hanoi",
    "Harare",
    "Harbin",
    "Hefei",
    "Ho Chi Minh City",
    "Hong Kong",
    "Hyderabad",
    "Imphal",
    "Istanbul",
    "Itanagar",
    "Jaipur",
    "Johannesburg",
    "Kabul",
    "Kanpur",
    "Karachi",
    "Kinshasa",
    "Kohima",
    "Kolkata",
    "Lagos",
    "Lahore",
    "Lima",
    "Los Angeles",
    "Luanda",
    "Lucknow",
    "Madrid",
    "Melbourne",
    "Mexico City",
    "Monterrey",
    "Mumbai",
    "Nagoya",
    "Nairobi",
    "Nanjing",
    "Osaka",
    "Panaji",
    "Patna",
    "Pusan",
    "Pyongyang",
    "Raipur",
    "Ranchi",
    "Rio De Janeiro",
    "Riyadh",
    "Saint Petersburg",
    "Santiago",
    "Shanghai",
    "Shenyang",
    "Shenzhen",
    "Shillong",
    "Shimla",
    "Singapore",
    "St. Petersburg",
    "Surat",
    "Sydney",
    "São Paulo",
    "Taipei",
    "Tehran",
    "Thiruvananthapuram",
    "Tianjin",
    "Tokyo",
    "Toronto",
    "Wuhan",
    "Yokohama",
)

val ADDRESS = listOf(
    "204, J Shankar Sheth Road, Near Gaiwadi, Girgaon",
    "15/15, N C C Gate No 6, Malwani Colony, Malad (west)",
    "25/2, Mrr Lane, Behind Hotel King, S J P Road",
    "1, Sweet Home, Os;road,road No5, Next To Bank Of Baroda, Mahim",
    "458 A, Vkk Menon Road, New Siddhapudur",
    "Shop No 5, Sukh Laxmi Apts, Shree Nagar, Wagle Est, Below Shree Hospital,"
)

val TALL_THUMBNAILS = listOf(
    "https://media.npr.org/assets/bakertaylor/covers/a/a-higher-loyalty/9781250192455_custom-bd588d4046de7b1bfa6178c3e94eac024a28c11b-s300-c85.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1664995844i/61102615.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1650240624i/58725016.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1626733115i/58591630.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1603739353i/55440232.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660472537i/59737212._SX600_.jpg",
    "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1601623827i/55264209._SX600_.jpg"
)
val VOUCHER_IMAGES = listOf(
    "https://d2czuodtiih8dn.cloudfront.net/data/files/baner_images/olive_gardern.png",
    "https://d2czuodtiih8dn.cloudfront.net/data/files/baner_images/amazon.png",
    "https://d2czuodtiih8dn.cloudfront.net/data/files/baner_images/hot_girl_rest.png",
)